---
- name: Configure persistent modules for Kubernetes
  ansible.builtin.template:
    src: templates/modules-load.conf.j2
    dest: "/etc/modules-load.d/kubernetes.conf"
    owner: root
    group: root
    mode: '0644'
- name: Add required modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ pre_kube_required_modules }}"
- name: Set persistent sysctl params for Kubernetes
  ansible.posix.sysctl:
    name: "{{ item['param'] }}"
    value: "{{ item['value'] }}"
    sysctl_file: /etc/sysctl.d/90-kubernetes.conf
    sysctl_set: true
    reload: true
    state: present
  loop: "{{ pre_kube_sysctls }}"
- name: Disable swap # noqa no-changed-when # The role should always ensure swap is disabled
  ansible.builtin.command: swapoff -a
- name: Remove swapfs
  ansible.posix.mount:
    path: none
    fstype: swap
    state: absent
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  ignore_errors: true # noqa ignore-errors # SELinux could be enabled on any repo or without a standard set of tools
  notify:
    - Reboot
- name: Disable ufw, if installed
  community.general.ufw:
    state: disabled
  ignore_errors: true # noqa ignore-errors # ufw is not consistently installed
- name: Disable firewalld, if present
  ansible.builtin.systemd:
    name: firewalld
    enabled: false
    masked: true
    state: stopped
  ignore_errors: true # noqa ignore-errors # firewalld is not consistently installed
