# (Re-)boot the lab servers
# yamllint disable rule:truthy rule:line-length
---
- name: (Re-)boot servers
  hosts: servers
  become: no
  gather_facts: no
  tasks:
    - name: Get IPMI secrets from Vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_url }}"
        ca_cert: "{{ root_ca | realpath }}"
        path: "{{ vault_ipmi_secrets_path }}"
        auth_method: token
        token_validate: no
      register: ipmi_secrets
      delegate_to: localhost
    - name: Cycle power through IPMI
      community.general.ipmi_power:
        name: "{{ ipmi_host }}"
        user: "{{ ipmi_secrets.secret.user }}"
        password: "{{ ipmi_secrets.secret.password }}"
        state: boot
      delegate_to: localhost
