# Playbook to repave servers via PXE
---
- name: Prepare for server repave from PXE
  hosts: shared
  become: true
  tasks:
    - name: Set PXE target on shared
      ansible.builtin.template:
        src: templates/tftp/pxelinux.cfg/lab_default_target.cfg.j2
        dest: /srv/tftp/{{ item }}/pxelinux.cfg/lab_default_target.cfg
        force: true
        owner: root
        group: root
        mode: '0644'
      loop:
        - bios
        - efi32
        - efi64
- name: Force reboot into PXE
  hosts: servers
  become: false
  gather_facts: false
  tasks:
    - name: Get IPMI secrets from Vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_url }}"
        ca_cert: "{{ root_ca | realpath }}"
        path: "{{ vault_ipmi_secrets_path }}"
        auth_method: token
        token_validate: false
      register: ipmi_secrets
      delegate_to: localhost
    - name: Set next boot to PXE through IPMI
      community.general.ipmi_boot:
        name: "{{ ipmi_host }}"
        user: "{{ ipmi_secrets.secret.user }}"
        password: "{{ ipmi_secrets.secret.password }}"
        bootdev: network
        persistent: false
      delegate_to: localhost
    - name: Cycle power through IPMI
      community.general.ipmi_power:
        name: "{{ ipmi_host }}"
        user: "{{ ipmi_secrets.secret.user }}"
        password: "{{ ipmi_secrets.secret.password }}"
        state: boot
      delegate_to: localhost
