# Shutdown the lab servers
# yamllint disable rule:line-length
---
- name: Power off servers
  hosts: servers
  become: false
  gather_facts: false
  tasks:
    - name: Get IPMI secrets from Vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_url }}"
        ca_cert: "{{ root_ca | realpath }}"
        path: "{{ vault_ipmi_secrets_path }}"
        auth_method: token
        token_validate: false
      register: ipmi_secrets
      delegate_to: localhost
    - name: Shutdown through IPMI
      community.general.ipmi_power:
        name: "{{ ipmi_host }}"
        user: "{{ ipmi_secrets.secret.user }}"
        password: "{{ ipmi_secrets.secret.password }}"
        state: shutdown
        timeout: 60
      delegate_to: localhost
      ignore_errors: true  # noqa ignore-errors
    - name: Power off through IPMI
      community.general.ipmi_power:
        name: "{{ ipmi_host }}"
        user: "{{ ipmi_secrets.secret.user }}"
        password: "{{ ipmi_secrets.secret.password }}"
        state: 'off'
      delegate_to: localhost
