---
galaxy_info:
  author: Matthew Emes
  description: Install cilium to kubernetes
  license: MIT
  min_ansible_version: '2.1'
  galaxy_tags: []
  platforms:
    - name: EL
      versions:
        - '8'
    - name: Ubuntu
      versions:
        - jammy
        - focal
dependencies: []
