# Configure the hosts that are part of the servers group
# yamllint disable rule:line-length
---
ansible_ssh_extra_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
# ESXi/vSphere
vcenter_ova_url: "{{ lab_shared_https_url }}/software/vcsa6.7.0-16046470-x86_64/vcsa/VMware-vCenter-Server-Appliance-6.7.0.44000-16046470_OVF10.ova"
vcenter_ova_path: /Volumes/shared/software/vcsa6.7.0-16046470-x86_64/vcsa/VMware-vCenter-Server-Appliance-6.7.0.44000-16046470_OVF10.ova
vcenter_machine: vcenter
vcenter_hostname: "{{ vcenter_machine }}.{{ lab_domain }}"
vcenter_url: "https://{{ vcenter_hostname }}/"
vcenter_config_url: "https://{{ vcenter_hostname }}:5480/"
vcenter_address: '172.17.1.1'
vcenter_vnet: vmgmt
vsphere_datacenter: lab
vsphere_cluster: cluster0
vsphere_dvswitch: dvSwitch0
# Kubernetes
crio_version: '1.23'
kubernetes_version: '1.23.5'
kubernetes_api_server: 'control.{{ lab_domain }}'
kubernetes_api_address: '172.17.1.2'
calico_version: v3.22.1
kubernetes_pod_cidr: 10.0.0.0/17
kubernetes_service_cidr: 10.1.0.0/22
kubernetes_external_cidr: 10.2.0.0/24
kubernetes_lb_cidr: 10.3.0.0/24
longhorn_version: v1.2.3
