# spell-checker: disable
---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        files: \.(yml|yaml|talismanrc)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.8.4
    hooks:
      - id: ansible-lint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by=required --hide=providers']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.29.1'
    hooks:
      - id: talisman-commit
