# spell-checker: disable
---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yml|yaml|talismanrc)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.58.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by=required --hide=providers']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  # Talisman can't be built from source in current pre-commit; invoke a locally
  # installed binary instead.
  - repo: local
    hooks:
      - id: local-talisman
        name: talisman
        entry: talisman --githook pre-commit
        stages:
          - commit
        pass_filenames: false
        types:
          - text
        language: system
