# Update shared server playbook
# In my lab, the shared group hosts both shared file services and vault services
# code: language=ansible
---
- name: Update shared services and files
  hosts: shared
  become: true
  roles:
    - shared
- name: Update Vault service
  hosts: vault
  become: true
  roles:
    - vault
