# Perform CentOS/RHEL specific tasks common to all hosts
---
- name: Add Kubernetes yum repo
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    # yamllint disable-line rule:line-length
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
- name: Install required packages
  ansible.builtin.package:
    name:
      - cri-tools
      - iproute-tc
      - "kubectl-{{ kubeadm_version }}"
      - "kubelet-{{ kubeadm_version }}"
      - "kubeadm-{{ kubeadm_version }}"
