# Lab hosts
---
all:
  hosts:
    vault.lab.acceleratedgcp.com:
    shared.lab.acceleratedgcp.com:
    vmm01.lab.acceleratedgcp.com:
    vmm02.lab.acceleratedgcp.com:
    vmm03.lab.acceleratedgcp.com:
  children:
    vault:
      hosts:
        vault.lab.acceleratedgcp.com:
    shared:
      hosts:
        shared.lab.acceleratedgcp.com:
    servers:
      hosts:
        vmm[01:03].lab.acceleratedgcp.com:
