# Lab hosts
---
all:
  hosts:
    vault.lab.acceleratedgcp.com:
      ansible_host: 172.17.0.2
      real_hostname: flipper.lab.acceleratedgcp.com
    shared.lab.acceleratedgcp.com:
      ansible_host: 172.17.0.2
      real_hostname: flipper.lab.acceleratedgcp.com
    vmm01.lab.acceleratedgcp.com:
      ansible_host: 172.17.0.4
      ipmi_host: 172.17.0.3
      real_hostname: gustav.lab.acceleratedgcp.com
    vmm02.lab.acceleratedgcp.com:
      ansible_host: 172.17.0.6
      ipmi_host: 172.17.0.5
      real_hostname: mystic.lab.acceleratedgcp.com
    vmm03.lab.acceleratedgcp.com:
      ansible_host: 172.17.0.8
      ipmi_host: 172.17.0.7
      real_hostname: eternal.lab.acceleratedgcp.com
    vcenter.lab.acceleratedgcp.com:
      ansible_host: 172.17.1.1
      ansible_user: root
  children:
    vault:
      hosts:
        vault.lab.acceleratedgcp.com:
    shared:
      hosts:
        shared.lab.acceleratedgcp.com:
    servers:
      hosts:
        vmm[01:03].lab.acceleratedgcp.com:
