# Perform Debian specific tasks for CRI-O
# yamllint disable rule:line-length
---
- name: Fetch repo key for CRI-O apt packages
  ansible.builtin.get_url:
    url: "{{ base_url }}stable:/cri-o:/{{ repo_version }}/{{ apt_repo_mapping[ansible_distribution] }}/Release.key"
    dest: /var/tmp/crio/crio.key
    owner: root
    group: root
    mode: '0640'
- name: Fetch repo key for stable CRI-O apt packages
  ansible.builtin.get_url:
    url: "{{ base_url }}stable/{{ apt_repo_mapping[ansible_distribution] }}/Release.key"
    dest: /var/tmp/crio/crio_stable.key
    owner: root
    group: root
    mode: '0640'
- name: Add repo key for CRI-O apt packages
  ansible.builtin.command:
    cmd: >-
      gpg --batch --yes --dearmor --output /usr/share/keyrings/crio.gpg
        /var/tmp/crio/crio.key
    creates: /usr/share/keyrings/crio.gpg
- name: Add repo key for stable CRI-O apt packages
  ansible.builtin.command:
    cmd: >-
      gpg --batch --yes --dearmor --output /usr/share/keyrings/crio_stable.gpg
        /var/tmp/crio/crio_stable.key
    creates: /usr/share/keyrings/crio_stable.gpg
- name: Fix repo key permissions
  ansible.builtin.file:
    path: "/usr/share/keyrings/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - crio.gpg
    - crio_stable.gpg
- name: Add CRI-O apt package repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/crio.gpg] {{ base_url }}stable:/cri-o:/{{ repo_version }}/{{ apt_repo_mapping[ansible_distribution] }}/ /"
    state: present
    filename: crio
    update_cache: true
- name: Add CRI-O stable apt package repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/crio_stable.gpg] {{ base_url }}stable/{{ apt_repo_mapping[ansible_distribution] }}/ /"
    state: present
    filename: crio_stable
    update_cache: true
