# Perform Ubuntu specific tasks for CRI-O
# yamllint disable rule:line-length
---
- name: Fetch Ubuntu repo key for CRI-O packages
  ansible.builtin.get_url:
    url: "{{ base_url }}stable:/cri-o:/{{ repo_version }}/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    dest: /tmp/crio.key
    owner: root
    group: root
    mode: '0640'
- name: Fetch Ubuntu repo key for stable packages
  ansible.builtin.get_url:
    url: "{{ base_url }}stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    dest: /tmp/crio_stable.key
    owner: root
    group: root
    mode: '0640'
- name: Add Ubuntu repo key for CRI-O packages
  ansible.builtin.command:
    cmd: gpg --dearmor --output /usr/share/keyrings/crio.gpg /tmp/crio.key
    creates: /usr/share/keyrings/crio.gpg
- name: Add Ubuntu repo key for stable packages
  ansible.builtin.command:
    cmd: gpg --dearmor --output /usr/share/keyrings/crio_stable.gpg /tmp/crio_stable.key
    creates: /usr/share/keyrings/crio_stable.gpg
- name: Fix Ubuntu repo key permissions
  ansible.builtin.file:
    path: "/usr/share/keyrings/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - crio.gpg
    - crio_stable.gpg
- name: Add Ubuntu CRI-O package repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/crio.gpg] {{ base_url }}stable:/cri-o:/{{ repo_version }}/xUbuntu_{{ ansible_distribution_version }}/ /"
    state: present
    filename: crio
- name: Add Ubuntu CRI-O OS stable packages repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/crio_stable.gpg] {{ base_url }}stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    state: present
    filename: crio_stable
