---
- name: Refresh apt cache
  ansible.builtin.apt:
    autoclean: true
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
- name: Update apt packages
  ansible.builtin.apt:
    name: '*'
    allow_change_held_packages: false
    allow_downgrade: false
    state: latest  # noqa package-latest
  when: ansible_os_family == "Debian"
- name: Refresh and update RPM packages
  ansible.builtin.dnf:
    name: '*'
    nobest: true
    state: latest  # noqa package-latest
    update_cache: true
  when: ansible_os_family == "RedHat"
- name: Remove unneeded apt dependencies
  ansible.builtin.apt:
    autoremove: true
  when: ansible_os_family == "Debian"
- name: Remove unneeded RPM dependencies
  ansible.builtin.dnf:
    autoremove: true
  when: ansible_os_family == "RedHat"
