---
required_modules:
  - br_netfilter
sysctls:
  - param: net.bridge.bridge-nf-call-iptables
    value: 1
  - param: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - param: net.ipv4.ip_forward
    value: 1
  - param: vm.nr_hugepages
    value: 2048
  - param: net.ipv6.conf.all.forwarding
    value: 1
