---
- name: Validate netplan
  ansible.builtin.command: netplan generate
  notify: Apply netplan
  changed_when: false
- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: true
- name: Update con vlan100
  ansible.builtin.command: nmcli con up {{ dataplane_device }}.100
  changed_when: true
