---
cgroup_driver: systemd
ipv4_extra_args: "{{ {'node-cidr-mask-size-ipv4': ipv4_node_mask | string} if (pod_cidrs | ansible.utils.ipv4 | length > 0) else {} }}"
ipv6_extra_args: "{{ {'node-cidr-mask-size-ipv6': ipv6_node_mask | string} if (pod_cidrs | ansible.utils.ipv6 | length > 0) else {} }}"
# Consistently choose a single host as the kubeadm init target in preference
# to run_once, etc. This helps the role to recover from temporary errors by
# reusing the same token and cert hashes already created.
init_target: "{{ ansible_play_hosts_all | map('extract', hostvars) | selectattr('k8s', 'defined') | selectattr('k8s.master', 'defined') | selectattr('k8s.master') | map(attribute='inventory_hostname') | list | sort | first }}"
