# Install Cilium as CNI
# yamllint disable rule:truthy rule:line-length
---
- name: Gather facts
  hosts: servers
  become: yes
  gather_facts: yes
- name: Install Cilium
  hosts: localhost
  become: no
  gather_facts: no
  vars:
    dataplane_device: 'bond0.100'
    bgp_peer: "{{ hostvars[groups['servers'][0]]['vlan100_addresses'] | ansible.utils.ipv4 | ansible.utils.ipaddr('1') | ansible.utils.ipaddr('address') | first }}"
  tasks:
    - name: Create BGP ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: bgp-config
            namespace: kube-system
          data:
            config.yaml: |
              peers:
                - peer-address: {{ bgp_peer }}
                  peer-asn: {{ bgp_peer_asn | default('64512') }}
                  my-asn: {{ bgp_asn | default('64513') }}
              address-pools:
                - name: default
                  protocol: bgp
                  addresses:
                    - {{ kubernetes_lb_cidr | default('10.3.0.0/24') }}
      tags:
        - init
    - name: Add Cilium helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/
      tags:
        - init
    - name: Install Cilium from chart
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_version }}"
        update_repo_cache: yes
        force: yes
        wait: yes
        release_namespace: kube-system
        values:
          bgp:
            enabled: true
            announce:
              loadbalancerIP: true
              podCIDR: true
          extraArgs:
            - "--devices={{ dataplane_device }}"
          ipam:
            mode: kubernetes
          loadbalancer:
            mode: dsr
          kubeProxyReplacement: strict
          k8s:
            requireIPv4PodCIDR: true
          k8sServiceHost: "{{ kubernetes_api_address }}"
          k8sServicePort: "{{ kubernetes_api_port | default(6443) }}"
          tunnel: disabled
          ipv4NativeRoutingCIDR: "{{ kubernetes_pod_cidr | default('10.0.0.0/16') }}"
      tags:
        - init
    - name: Wait for Cilium to be ready
      kubernetes.core.k8s_info:
        kind: DaemonSet
        name: cilium
        namespace: kube-system
      register: cilium_ready
      until: cilium_ready.resources | json_query('[0].status | numberReady == desiredNumberScheduled')
      delay: 10
      retries: 6
      tags:
        - init
