# Install Cilium as CNI
# yamllint disable rule:truthy rule:line-length
---
- name: Install Cilium
  hosts: servers
  become: no
  tasks:
    - name: Add Cilium helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/
      run_once: yes
      delegate_to: 127.0.0.1
      tags:
        - init
    - name: Install Cilium from chart
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_version }}"
        release_namespace: kube-system
        values:
          kubeProxyReplacement: strict
          k8sServiceHost: "{{ kubernetes_api_address }}"
          k8sServicePort: "6443"
      run_once: yes
      delegate_to: 127.0.0.1
      tags:
        - init
    - name: Wait for Cilium to be ready
      kubernetes.core.k8s_info:
        kind: DaemonSet
        name: cilium
        namespace: kube-system
      register: cilium_ready
      until: cilium_ready.resources | json_query('[0].status | numberReady == desiredNumberScheduled')
      delay: 10
      retries: 6
      run_once: yes
      delegate_to: 127.0.0.1
      tags:
        - init
