# Install Cilium as CNI
# yamllint disable rule:truthy rule:line-length
---
- name: Install Cilium
  hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: Create BGP ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: bgp-config
            namespace: kube-system
          data:
            config.yaml: |
              peers:
                - peer-address: 172.24.0.1
                  peer-asn: 64512
                  my-asn: 64513
              address-pools:
                - name: default
                  protocol: bgp
                  addresses:
                    - {{ kubernetes_lb_cidr | default('10.3.0.0/24') }}
      tags:
        - init
    - name: Add Cilium helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/
      tags:
        - init
    - name: Install Cilium from chart
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_version }}"
        update_repo_cache: yes
        force: yes
        wait: yes
        release_namespace: kube-system
        values:
          bgp:
            enabled: true
            announce:
              loadbalancerIP: true
              podCIDR: true
          ipam:
            mode: kubernetes
          loadbalancer:
            mode: dsr
          kubeProxyReplacement: strict
          k8s:
            requireIPv4PodCIDR: true
          k8sServiceHost: "{{ kubernetes_api_address }}"
          k8sServicePort: "6443"
          tunnel: disabled
          ipv4NativeRoutingCIDR: "{{ kubernetes_pod_cidr | default('10.0.0.0/17') }}"
      tags:
        - init
    - name: Wait for Cilium to be ready
      kubernetes.core.k8s_info:
        kind: DaemonSet
        name: cilium
        namespace: kube-system
      register: cilium_ready
      until: cilium_ready.resources | json_query('[0].status | numberReady == desiredNumberScheduled')
      delay: 10
      retries: 6
      tags:
        - init
