# Install kubernetes on hosts
# yamllint disable rule:truthy
---
- name: Prepare all hosts for longhorn
  hosts: servers
  become: yes
  tasks:
    - name: Install longhorn pre-requisites on Ubuntu
      ansible.builtin.package:
        name:
          - open-iscsi
          - nfs-common
        state: present
      when: ansible_distribution == "Ubuntu"
      tags:
        - base
    - name: Install longhorn pre-requisites on CentOS/RHEL
      ansible.builtin.package:
        name:
          - iscsi-initiator-utils
          - nfs-utils
        state: present
      when: ansible_os_family == "RedHat"
      tags:
        - base
    - name: Enable iscsid unit
      ansible.builtin.systemd:
        name: iscsid
        enabled: yes
        state: restarted
        daemon_reload: yes
      tags:
        - base
- name: Install longhorn
  hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: Deploy longhorn
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/deploy/longhorn.yaml
      tags:
        - init
    - name: Use longhorn as default storage class
      kubernetes.core.k8s:
        state: patched
        kind: StorageClass
        name: longhorn
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: 'true'
      tags:
        - init
