# Playbook to repave servers via PXE
# yamllint disable rule:truthy rule:line-length
---
- name: Prepare for server repave from PXE
  hosts: shared
  become: yes
  tasks:
    - name: set PXE target on shared
      ansible.builtin.template:
        src: templates/shared/tftp/pxelinux.cfg/lab_default_target.cfg.j2
        dest: /srv/tftp/pxelinux.cfg/lab_default_target.cfg
        force: yes
        owner: root
        group: root
        mode: 0644
- name: Force reboot into PXE
  hosts: servers
  become: no
  gather_facts: no
  vars:
    ipmi_vault_options: "secret={{ vault_kv2_ipmi_secrets_path }} url={{ vault_url }} ca_cert={{ root_ca }}"
    ipmi_secrets: "{{ lookup('community.hashi_vault.hashi_vault', ipmi_vault_options) }}"
  tasks:
    - name: set next boot to PXE through IPMI
      community.general.ipmi_boot:
        name: "{{ ipmi_host }}"
        user: "{{ ipmi_secrets.user }}"
        password: "{{ ipmi_secrets.password }}"
        bootdev: network
        persistent: no
      delegate_to: 127.0.0.1
    - name: cycle power through IPMI
      community.general.ipmi_power:
        name: "{{ ipmi_host }}"
        user: "{{ ipmi_secrets.user }}"
        password: "{{ ipmi_secrets.password }}"
        state: boot
      delegate_to: 127.0.0.1
