# Update shared server
# yamllint disable rule:truthy rule:line-length
---
- name: Update shared services and files
  hosts: shared
  become: yes
  vars:
    ks_vault_options: "secret={{ vault_kv2_kickstart_secrets_path }} url={{ vault_url }} ca_cert={{ root_ca }}"
    ks_secrets: "{{ lookup('community.hashi_vault.hashi_vault', ks_vault_options) }}"
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - samba
          - nfs-kernel-server
          - rpcbind
          - tftpd-hpa
          - pxelinux
          - syslinux
          - "debian-installer-{{ ansible_distribution_major_version }}-netboot-amd64"
          - nginx
        state: present
      tags:
        - init
    - name: Manage shared file system configs
      ansible.builtin.template:
        src: "templates/shared/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        force: yes
        owner: root
        group: root
        mode: 0644
      loop:
        - exports
        - default/nfs-common
        - default/nfs-kernel-server
        - samba/smb.conf
      notify:
        - restart NFS
        - restart Samba
      tags:
        - init
    - name: Set NFS kernel modprobe file
      ansible.builtin.template:
        src: templates/shared/etc/modprobe.d/nfs-modules.conf.j2
        dest: "/etc/modprobe.d/nfs-modules.conf"
        owner: root
        group: root
        mode: 0644
      tags:
        - init
    - name: Set NFS kernel module params
      ansible.posix.sysctl:
        name: "{{ item['param'] }}"
        value: "{{ item['value'] }}"
        sysctl_file: /etc/sysctl.d/90-nfs-static-ports.conf
        sysctl_set: yes
        # If modules aren't loaded yet, the param keys will be undefined; ignore
        ignoreerrors: yes
        reload: yes
        state: present
      loop:
        - param: fs.nfs.nfs_callback_tcpport
          value: 32764
        - param: fs.nfs.nlm_tcpport
          value: 32768
        - param: fs.nfs.nlm_udpport
          value:
      tags:
        # Emes - reverted
        - never
    - name: Create directories for TFTP
      ansible.builtin.file:
        path: "/srv/{{ item }}"
        state: directory
        owner: tftp
        group: root
        mode: 0755
      loop:
        - tftp
        - tftp/boot
        - tftp/boot/debian{{ ansible_distribution_major_version }}-x86_64
        - tftp/boot/dell_emc_esxi67-x86_64
        - tftp/bios
        - tftp/bios/pxelinux.cfg
        - tftp/efi32
        - tftp/efi32/pxelinux.cfg
        - tftp/efi64
        - tftp/efi64/pxelinux.cfg
        - tftp/esxi
        - tftp/esxi/pxelinux.cfg
      tags:
        - pxe
    - name: Copy syslinux files for TFTP
      ansible.builtin.copy:
        remote_src: yes
        src: /usr/lib/syslinux/modules/{{ item }}/
        dest: /srv/tftp/{{ item }}/
        force: yes
        owner: tftp
        group: root
      loop:
        - bios
        - efi32
        - efi64
      tags:
        - pxe
    - name: Copy pxelinux BIOS files for TFTP
      ansible.builtin.copy:
        remote_src: yes
        src: "/usr/lib/PXELINUX/"
        dest: "/srv/tftp/bios/"
        force: yes
        owner: tftp
        group: root
      tags:
        - pxe
    - name: Copy syslinux EFI files for TFTP
      ansible.builtin.copy:
        remote_src: yes
        src: "/usr/lib/SYSLINUX.EFI/{{ item }}/"
        dest: "/srv/tftp/{{ item }}/"
        force: yes
        owner: tftp
        group: root
      loop:
        - efi32
        - efi64
      tags:
        - pxe
    - name: Copy Debian netboot files for TFTP
      ansible.builtin.copy:
        remote_src: yes
        src: "/usr/lib/debian-installer/images/{{ ansible_distribution_major_version }}/amd64/text/debian-installer/amd64/{{ item }}"
        dest: "/srv/tftp/boot/debian{{ ansible_distribution_major_version }}-x86_64/{{ item }}"
        force: yes
        owner: tftp
        group: root
      loop:
        - linux
        - initrd.gz
      tags:
        - pxe
    - name: Copy static boot configurations
      ansible.builtin.copy:
        src: "files/shared/tftp/boot/"
        dest: "/srv/tftp/boot/"
        force: yes
        owner: tftp
        group: root
        mode: 0644
      tags:
        - pxe
    - name: Copy static PXE configurations
      ansible.builtin.copy:
        src: "files/shared/tftp/pxelinux.cfg/"
        dest: "/srv/tftp/{{ item }}/pxelinux.cfg/"
        force: yes
        owner: tftp
        group: root
        mode: 0644
      loop:
        - bios
        - efi32
        - efi64
      tags:
        - pxe
    - name: Copy static ESXi PXE configurations
      ansible.builtin.copy:
        src: "files/shared/tftp/esxi/pxelinux.cfg/"
        dest: "/srv/tftp/esxi/pxelinux.cfg/"
        force: yes
        owner: tftp
        group: root
        mode: 0644
      tags:
        - pxe
    - name: Copy templated BIOS PXE configurations
      vars:
        - bios: true
      ansible.builtin.template:
        src: "templates/shared/tftp/pxelinux.cfg/{{ item }}.j2"
        dest: "/srv/tftp/bios/pxelinux.cfg/{{ item }}"
        force: yes
        owner: tftp
        group: root
        mode: 0644
      loop:
        - centos.cfg
        - debian.cfg
        - default
        - kali.cfg
        - lab_autoprovision.cfg
        - lab_default_target.cfg
        - redhat.cfg
        - ubuntu.cfg
        - tools.cfg
      tags:
        - pxe
    - name: Copy templated EFI32 PXE configurations
      ansible.builtin.template:
        src: "templates/shared/tftp/pxelinux.cfg/{{ item }}.j2"
        dest: "/srv/tftp/efi32/pxelinux.cfg/{{ item }}"
        force: yes
        owner: tftp
        group: root
        mode: 0644
      loop:
        - centos.cfg
        - debian.cfg
        - default
        - kali.cfg
        - lab_autoprovision.cfg
        - lab_default_target.cfg
        - redhat.cfg
        - ubuntu.cfg
        - tools.cfg
      tags:
        - pxe
    - name: Copy templated EFI64 PXE configurations
      ansible.builtin.template:
        src: "templates/shared/tftp/pxelinux.cfg/{{ item }}.j2"
        dest: "/srv/tftp/efi64/pxelinux.cfg/{{ item }}"
        force: yes
        owner: tftp
        group: root
        mode: 0644
      loop:
        - centos.cfg
        - debian.cfg
        - default
        - kali.cfg
        - lab_autoprovision.cfg
        - lab_default_target.cfg
        - redhat.cfg
        - ubuntu.cfg
        - tools.cfg
      tags:
        - pxe
    - name: Copy templated ESXi lab configuration
      ansible.builtin.template:
        src: templates/shared/tftp/boot/dell_emc_esxi67-x86_64/lab.cfg.j2
        dest: /srv/tftp/boot/dell_emc_esxi67-x86_64/lab.cfg
        force: yes
        owner: tftp
        group: root
        mode: 0644
      tags:
        - pxe
    - name: Create hard-links for server MACs to autoprovision via BIOS
      ansible.builtin.file:
        src: "/srv/tftp/bios/pxelinux.cfg/lab_autoprovision.cfg"
        path: "/srv/tftp/bios/pxelinux.cfg/{{ item }}"
        state: hard
        force: yes
        owner: tftp
        group: root
        mode: 0644
      loop: "{{ autoprovision_macs | map('regex_replace', ':', '-') | map('lower') | list }}"
      tags:
        - pxe
    - name: Create hard-links for server MACs to autoprovision via EFI32
      ansible.builtin.file:
        src: "/srv/tftp/efi32/pxelinux.cfg/lab_autoprovision.cfg"
        path: "/srv/tftp/efi32/pxelinux.cfg/{{ item }}"
        state: hard
        force: yes
        owner: tftp
        group: root
        mode: 0644
      loop: "{{ autoprovision_macs | map('regex_replace', ':', '-') | map('lower') | list }}"
      tags:
        - pxe
    - name: Create hard-links for server MACs to autoprovision via EFI64
      ansible.builtin.file:
        src: "/srv/tftp/efi64/pxelinux.cfg/lab_autoprovision.cfg"
        path: "/srv/tftp/efi64/pxelinux.cfg/{{ item }}"
        state: hard
        force: yes
        owner: tftp
        group: root
        mode: 0644
      loop: "{{ autoprovision_macs | map('regex_replace', ':', '-') | map('lower') | list }}"
      tags:
        - pxe
    - name: Start tftpd-hpa
      ansible.builtin.service:
        name: tftpd-hpa
        state: started
        enabled: yes
      tags:
        - pxe
    - name: Update CA cert
      ansible.builtin.copy:
        src: ../ca/acceleratedgcp-root-ca.pem
        dest: /usr/local/share/ca-certificates/acceleratedgcp-root-ca.crt
        force: yes
        owner: root
        group: root
        mode: 0644
      notify:
        - update ca certs
      tags:
        - http
    - name: Update HTTPS TLS cert
      ansible.builtin.copy:
        src: "../certs/{{ lab_shared_host }}.pem"
        dest: "/etc/ssl/certs/{{ lab_shared_host }}.pem"
        force: yes
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx
      tags:
        - http
    - name: Update HTTPS TLS key
      ansible.builtin.copy:
        src: "../certs/{{ lab_shared_host }}.key"
        dest: "/etc/ssl/private/{{ lab_shared_host }}.key"
        force: yes
        owner: root
        group: root
        mode: 0600
      notify:
        - restart nginx
      tags:
        - http
    - name: Configure nginx for shared
      ansible.builtin.template:
        src: templates/shared/nginx/shared.j2
        dest: /etc/nginx/sites-available/shared
        force: yes
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx
      tags:
        - http
    - name: Enable shared nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/shared
        dest: /etc/nginx/sites-enabled/shared
        owner: root
        group: root
        state: link
      notify:
        - restart nginx
    - name: Disable default nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx
      tags:
        - http
    - name: Create directories for shared files
      ansible.builtin.file:
        path: "/srv/shared/{{ item }}"
        state: directory
        owner: root
        group: shared
        mode: 0775
      loop:
        - certs
        - cloud-init
        - cloud-init/focal
        - d-i
        - d-i/bionic
        - el8
        - esxi
        - keys
        - kubernetes
        - scripts
      tags:
        - http
        - pxe
    - name: Copy CA file
      ansible.builtin.copy:
        src: ../ca/acceleratedgcp-root-ca.pem
        dest: /srv/shared/certs/
        force: yes
        owner: root
        group: shared
        mode: 0664
      tags:
        - http
        - pxe
    - name: Update static key files
      ansible.builtin.copy:
        src: "files/shared/keys/{{ item }}"
        dest: "/srv/shared/keys/{{ item }}"
        force: yes
        owner: root
        group: shared
        mode: 0664
      loop:
        - 0x1285491434D8786F.asc
        - 0x3CA66B4946770C59.asc
        - 0x756ba70b1019ced6.asc
        - 0xca77951d23b66a9d.asc
        - hashicorp.asc
        - RPM-GPG-KEY-CentOS-Official.asc
        - RPM-GPG-KEY-elrepo.asc
        - RPM-GPG-KEY-redhat-release.asc
      tags:
        - http
        - pxe
    - name: Update templated lab files
      vars:
        administrator_password: "{{ ks_secrets.administrator }}"
        memes_password: "{{ ks_secrets.memes }}"
        rhn_password: "{{ ks_secrets.rhn_password }}"
        rhn_user: "{{ ks_secrets.rhn_user }}"
        ssh_pubkey: "{{ ks_secrets.ssh_pubkey }}"
        root_password: "{{ ks_secrets.root }}"
      ansible.builtin.template:
        src: "templates/shared/{{ item }}.j2"
        dest: "/srv/shared/{{ item }}"
        force: yes
        owner: root
        group: shared
        mode: 0664
      loop:
        - cloud-init/focal/user-data
        - cloud-init/focal/meta-data
        - d-i/bionic/preseed.cfg
        - el8/centos8-minimal.ks
        - esxi/esxi67.ks
        - el8/rhel8-minimal.ks
        - scripts/post-onboard-centos8.sh
        - scripts/post-onboard-debian.sh
        - scripts/post-onboard-el8.sh
        - scripts/post-onboard-rhel8.sh
        - scripts/post-onboard-ssh-pubkey.sh
        - scripts/post-onboard-ubuntu-netplan.sh
        - scripts/pre-onboard-el8.sh
      tags:
        - http
        - pxe

  handlers:
    - name: restart NFS
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted
    - name: restart Samba
      ansible.builtin.service:
        name: smbd
        state: restarted
    - name: update ca certs
      ansible.builtin.command: /usr/sbin/update-ca-certificates
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
