# Manage Vault service
# yamllint disable rule:truthy rule:line-length
---
- name: Install/update Vault service
  hosts: vault
  become: yes
  tasks:
    - name: Add Hashicorp apt key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      when: ansible_os_family == "Debian"
    - name: Add Hashicorp apt repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
      when: ansible_os_family == "Debian"
    - name: Add Hashicorp yum repo
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == "RedHat"
    - name: Install Vault
      ansible.builtin.package:
        name: vault
        state: present
    - name: Update Vault configuration
      ansible.builtin.template:
        src: templates/vault.d/{{ item }}.j2
        dest: "/etc/vault.d/{{ item }}"
        force: yes
        owner: root
        group: vault
        mode: 0640
      loop:
        - vault.hcl
        - vault.env
      notify:
        - restart Vault
    - name: Copy Vault TLS files
      ansible.builtin.copy:
        src: "../certs/{{ item }}"
        dest: "{{ vault_home }}/tls/{{ item }}"
        force: yes
        owner: root
        group: vault
        mode: 0640
      loop:
        - "{{ vault_host }}.pem"
        - "{{ vault_host }}.key"
      notify:
        - restart Vault
    - name: Add GCP creds
      ansible.builtin.copy:
        src: "{{ vault_gcp_sa_creds_file }}"
        dest: "{{ vault_home }}/vault-sa.json"
        force: yes
        owner: root
        group: vault
        mode: 0640
      notify:
        - restart Vault
    - name: Enable systemd unit
      ansible.builtin.service:
        name: vault
        enabled: yes
        state: started

  handlers:
    - name: restart Vault
      ansible.builtin.service:
        name: vault
        state: restarted
