# Update shared server
# yamllint disable rule:truthy
---
- name: Update Vault service
  hosts: vault
  become: yes
  tasks:
    - name: Vault group
      ansible.builtin.group:
        name: vault
        system: yes
    - name: Vault user
      ansible.builtin.user:
        name: vault
        group: vault
        append: no
        system: yes
        shell: /bin/false
        password: "!"
        create_home: false
        home: "{{ vault_home }}"
        state: present
    - name: Set vault home permissions
      ansible.builtin.file:
        path: "{{ vault_home }}"
        state: directory
        mode: 0750
        owner: root
        group: vault
    - name: Update Vault configuration
      ansible.builtin.template:
        src: templates/vault/config.hcl.j2
        dest: "{{ vault_home }}/config.hcl"
        force: yes
        owner: vault
        group: vault
        mode: 0640
      notify:
        - restart Vault
    - name: Copy Vault TLS files
      ansible.builtin.copy:
        src: "../certs/{{ item }}"
        dest: "{{ vault_home }}/{{ item }}"
        force: yes
        owner: vault
        group: vault
        mode: 0640
      loop:
        - "{{ vault_host }}.pem"
        - "{{ vault_host }}.key"
      notify:
        - restart Vault
    - name: Add GCP creds
      ansible.builtin.copy:
        src: "{{ vault_gcp_sa_creds_file }}"
        dest: "{{ vault_home }}/vault-sa.json"
        force: yes
        owner: vault
        group: vault
        mode: 0640
      notify:
        - restart Vault
    - name: Install systemd unit
      ansible.builtin.template:
        src: templates/vault/vault.service.j2
        dest: /etc/systemd/system/vault.service
        force: yes
        owner: root
        group: root
        mode: 0644
      notify:
        - restart Vault
    - name: Enable systemd unit
      ansible.builtin.service:
        name: vault
        enabled: yes
        state: started

  handlers:
    - name: restart Vault
      ansible.builtin.service:
        name: vault
        state: restarted
