# These github actions will update Terraform section(s) of README(s), and
# perform linting using pre-commit.
# yamllint disable rule:line-length
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install terraform-docs
        run: |
          sudo curl -sL --output - https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz | tar xzf - -C /usr/local/bin
          sudo chmod 0755 /usr/local/bin/terraform-docs
      - name: install talisman
        run: |
          sudo curl -sLo /usr/local/bin/talisman https://github.com/thoughtworks/talisman/releases/download/v1.27.0/talisman_linux_amd64
          sudo chmod 0755 /usr/local/bin/talisman
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - uses: pre-commit/action@v3.0.0
